minimum_pre_commit_version: "2.9.3"

repos:
  - repo: https://github.com/ashanbrown/gofmts
    rev: v0.1.4
    hooks:
      - id: gofmts

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.43.0
    hooks:
      - id: golangci-lint
