# Golang CircleCI 2.1 configuration file for terraform-provider-launchdarkly-private tests
version: 2.1

orbs:
  go: circleci/go@1.7.0
  linter: talkiq/linter@1.4.1

jobs:
  test:
    executor:
      name: go/default
      tag: &go_version "1.16.10"

    steps:
      - checkout
      - go/mod-download-cached
      - run:
          name: Run unit tests
          command: TESTARGS="-v" make test
      - run:
          name: Test Data Sources
          command: TESTARGS="-run TestAccDataSource" make testacc
      - run:
          name: Test Access Token Resource
          command: TESTARGS="-run TestAccAccessToken" make testacc
      - run:
          name: Test Audit Log Subscription Resource
          command: TESTARGS="-run TestAccAuditLogSubscription" make testacc
      - run:
          name: Test Custom Role Resource
          command: TESTARGS="-run TestAccCustomRole" make testacc
      - run:
          name: Test Destination Resource
          command: TESTARGS="-run TestAccDestination" make testacc
      - run:
          name: Test Environment Resource
          command: TESTARGS="-run TestAccEnvironment" make testacc
      - run:
          name: Test Feature Flag Resource
          command: TESTARGS="-run TestAccFeatureFlag" make testacc
      - run:
          name: Test Feature Flag Environment Resource
          command: TESTARGS="-run TestAccFeatureFlagEnvironment" make testacc
      - run:
          name: Test Flag Trigger Resource
          command: TESTARGS="-run TestAccFlagTrigger" make testacc
      - run:
          name: Test Metric Resource
          command: TESTARGS="-run TestAccMetric" make testacc
      - run:
          name: Test Project Resource
          command: TESTARGS="-run TestAccProject" make testacc
      - run:
          name: Test Relay Proxy Configuration Resource
          command: TESTARGS="-run TestAccRelayProxy" make testacc
      - run:
          name: Test Segment Resource
          command: TESTARGS="-run TestAccSegment" make testacc
      - run:
          name: Test Team Members
          command: |
            TESTARGS="-run TestAccTeamMember_CreateGeneric" make testacc
            TESTARGS="-run TestAccTeamMember_UpdateGeneric" make testacc
            TESTARGS="-run TestAccTeamMember_CreateWithCustomRole" make testacc
            TESTARGS="-run TestAccTeamMember_UpdateWithCustomRole" make testacc
      - run:
          name: Test Webhook Resource
          command: TESTARGS="-run TestAccWebhook" make testacc

  lint:
    executor:
      name: go/default
      tag: *go_version

    steps:
      - checkout
      - run:
          name: Install python
          command: |
            sudo apt update
            sudo apt install python3-pip python-is-python3
      - linter/pre-commit

workflows:
  main:
    jobs:
      - test
      - lint
