# Golang CircleCI 2.1 configuration file for terraform-provider-launchdarkly-private tests
version: 2.1

orbs:
  go: circleci/go@1.7.0

jobs:
  build:
    executor:
      name: go/default
      tag: "1.16"

    steps:
      - checkout
      - go/mod-download-cached
      - run:
          name: go vet
          command: make vet
      - run:
          name: Run unit tests
          command: TESTARGS="-v" make test
      - run:
          name: Test Data Sources
          command: TESTARGS="-run TestAccDataSource" make testacc
      - run:
          name: Test Access Token Resource
          command: TESTARGS="-run TestAccAccessToken" make testacc
      - run:
          name: Test Custom Role Resource
          command: TESTARGS="-run TestAccCustomRole" make testacc
      - run:
          name: Test Destination Resource
          command: TESTARGS="-run TestAccDestination" make testacc
      - run:
          name: Test Environment Resource
          command: TESTARGS="-run TestAccEnvironment" make testacc
      - run:
          name: Test Feature Flag Resource
          command: TESTARGS="-run TestAccFeatureFlag" make testacc
      - run:
          name: Test Feature Flag Environment Resource
          command: TESTARGS="-run TestAccFeatureFlagEnvironment" make testacc
      - run:
          name: Test Project Resource
          command: TESTARGS="-run TestAccProject" make testacc
      - run:
          name: Test Segment Resource
          command: TESTARGS="-run TestAccSegment" make testacc
      - run:
          name: Test Team Members
          command: |
            TESTARGS="-run TestAccTeamMember_CreateGeneric" make testacc
            TESTARGS="-run TestAccTeamMember_UpdateGeneric" make testacc
            TESTARGS="-run TestAccTeamMember_CreateWithCustomRole" make testacc
            TESTARGS="-run TestAccTeamMember_UpdateWithCustomRole" make testacc
      - run:
          name: Test Webhook Resource
          command: TESTARGS="-run TestAccWebhook" make testacc

workflows:
  main:
    jobs:
      - build
